---
version: "2"
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    enabled: true
    config:
      threshold: 30
  similar-code:
    enabled: true
    config:
      threshold: 36
  identical-code:
    enabled: true
    config:
      threshold: 18
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.rb"
exclude_paths:
- spec/
- Gemfile.lock
- lib/push_to_dashboard.rb